#!/bin/bash
set -e
set +x

BASE_DIR=`cd "$(dirname "$0")"; pwd`

source "$BASE_DIR"/functions/basic

load_config
packages_install

$DOTFILES_INSTALL && \
    dotfiles_install || \
    warning "dotfiles configured to not be installed!"

$SDKMAN_INSTALL && \
    sdkman_install || \
    warning "sdkman configured to not be installed!"
