#!/bin/bash
set -e
set +x

BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/functions/basic

echo "TODO: this scripts needs to be fixed to used with curl"
exit 0

pre_install=$BASE_DIR/linux/`distro_name`/pre-install

if ! [ -f "$pre_install" ]
then
    echo "File not found: $pre_install"
    exit 1
fi

bash "$pre_install"
load_config
install_this_repo
