#!/bin/bash
set -e
set -x

sudo apt-get install -y git

repo=${repo:-paulojeronimo/dev-env}
repo_url=https://github.com/$repo
project_dir=~/Projects/github.com/`dirname "$repo"`

mkdir -p $project_dir
cd $project_dir
git clone $repo_url
cd `basename "$repo"`

./install
